global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prometheus-stack-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:

  - job_name: 'prometheus'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'machine-vm'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
      - targets: ['cadvisor:8080']

  # When running Docker, you can access host services using the IP address of the docker0 interface (Docker's default bridge network).
  # The IP address to use to access the host is:
  # - '172.17.0.1' for linux
  # - 'docker.for.mac.host.internal' for Mac

  - job_name: 'opendj0'

    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /metrics/prometheus

    basic_auth:
      username: 'monitor'
      password: 'password'

    static_configs:
      - targets: ['172.17.0.1:8080']

  - job_name: 'opendj1'

    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /metrics/prometheus

    basic_auth:
      username: 'monitor'
      password: 'password'

    static_configs:
      - targets: ['172.17.0.1:8081']

  - job_name: 'opendj2'

    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /metrics/prometheus

    static_configs:
      - targets: ['172.17.0.1:8082']

###############
# Data source #
###############
# For the moment, need to manually add a Prometheus data source named "Prometheus DJ" with URL "http://prometheus:9090"
# See "Adding datasource without using the web gui" at https://github.com/grafana/grafana/issues/1789
# http://docs.grafana.org/http_api/data_source/

#############
# Dashboard #
#############
# http://docs.grafana.org/http_api/dashboard/
