global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prometheus-stack-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:

  - job_name: 'prometheus'

    scrape_interval: 5s
    scrape_timeout: 10s

    target_groups:
      - targets: ['localhost:9090']

  - job_name: 'machine-vm'

    scrape_interval: 5s
    scrape_timeout: 10s

    target_groups:
      - targets: ['cadvisor:8080']

  - job_name: 'metrics-gateway'

    scrape_interval: 5s
    scrape_timeout: 10s

    target_groups:
      - targets: ['metrics-gateway:9091']